replace-all: melhorias de código

diff --git a/bin/replace-all b/bin/replace-all
--- a/bin/replace-all
+++ b/bin/replace-all
@@ -3,13 +3,14 @@
 # replace all
 # Replace all occurences of 'pattern' by 'subject' in 'folder'
 #
+##
 
-### Configuration
+### Settings
 
-PROGRAM_NAME="$( basename "$BASH_SOURCE" )"
+Program="$( basename "$BASH_SOURCE" )"
 
-[ $# -lt 3 ] && {
-    echo "${PROGRAM_NAME}: missing operands."
+[[ $# < 2 ]] && {
+    echo "${Program}: missing operands." >&2
     exit 1
 }
 
@@ -19,11 +20,17 @@ pattern="$1"
 subject="$2"
 folder="$3"
 
+[ -z "$3" ] && folder="."
+
 echo -e "\nReplacing '$pattern' with '$subject' in all files inside '$folder', please wait...\n"
 
-fgrep -r "$pattern" "$folder" | cut -d ':' -f 1 | sort | uniq | fgrep -v '.git' |
-    xargs -I '{}' sed -ri 's/'"$pattern"'/'"$subject"'/g' '{}' ||
-        exit 1
+fgrep -r "$pattern" "$folder" \
+    | cut -d ':' -f 1 \
+    | sort \
+    | uniq \
+    | fgrep -v '.git' \
+    | xargs -I '{}' sed -ri 's|'"$pattern"'|'"$subject"'|g' '{}' \
+    || exit 1
 
 echo -e "\nDone.\n"
 
